// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// TlscheckTimeLeftAttributeKey specifies the key of an attribute for the tlscheck.time_left metric.
type TlscheckTimeLeftAttributeKey string

const (
	TlscheckTimeLeftAttributeKeyTlscheckX509Issuer TlscheckTimeLeftAttributeKey = "tlscheck.x509.issuer"
	TlscheckTimeLeftAttributeKeyTlscheckX509Cn     TlscheckTimeLeftAttributeKey = "tlscheck.x509.cn"
	TlscheckTimeLeftAttributeKeyTlscheckX509San    TlscheckTimeLeftAttributeKey = "tlscheck.x509.san"
)

// TlscheckTimeLeftConfig provides config for the tlscheck.time_left metric.
type TlscheckTimeLeftConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                         `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TlscheckTimeLeftAttributeKey `mapstructure:"attributes"`
}

func (ms *TlscheckTimeLeftConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *TlscheckTimeLeftConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case TlscheckTimeLeftAttributeKeyTlscheckX509Issuer, TlscheckTimeLeftAttributeKeyTlscheckX509Cn, TlscheckTimeLeftAttributeKeyTlscheckX509San:
		default:
			return fmt.Errorf("metric tlscheck.time_left doesn't have an attribute %v, valid attributes: [tlscheck.x509.issuer, tlscheck.x509.cn, tlscheck.x509.san]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for tlscheck metrics.
type MetricsConfig struct {
	TlscheckTimeLeft TlscheckTimeLeftConfig `mapstructure:"tlscheck.time_left"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		TlscheckTimeLeft: TlscheckTimeLeftConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []TlscheckTimeLeftAttributeKey{TlscheckTimeLeftAttributeKeyTlscheckX509Issuer, TlscheckTimeLeftAttributeKeyTlscheckX509Cn, TlscheckTimeLeftAttributeKeyTlscheckX509San},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for tlscheck resource attributes.
type ResourceAttributesConfig struct {
	TlscheckTarget ResourceAttributeConfig `mapstructure:"tlscheck.target"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		TlscheckTarget: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for tlscheck metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
